#     required fields: title, isbn, publisher_id
#     optional fields: year, author, pages
#     publisher_id should be an id of existing publisher
#     isbn should be unique
# Create a new book
POST http://localhost:3000/books
Authorization: 50867f1d-60e2-42d6-a9fd-a0c78c459046
Content-Type: application/json

{
  "title": "Test3",
  "isbn": "9780345391801",
  "PublisherId": 1,
  "author": "Marwan Samamreh"
}

###
POST http://localhost:3000/users/sign-up
Content-Type: application/json

{
  "username": "MarwanTest6",
  "email": "marwan@test.com",
  "password": "123124"
}

###
post http://localhost:3000/users/sign-in
Content-Type: application/json

{
  "username": "MarwanTest6",
  "password": "123124"
}

### Sign Out
GET http://localhost:3000/users/sign-out
Authorization: 0b193e76-8e66-4be0-91cd-2c34aa441ffc


POST http://localhost:3000/customers/rent-book
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjoyLCJpYXQiOjE3MDQyODE1OTAsImV4cCI6MTcwNDI4MTcxMH0.TK5x6cQL_vvhp62FDDM7VeDjTSev3tdi7dBLkoOUNA8
Content-Type: application/json

{
  "bookId": 1
}

### Search for a book
GET http://localhost:3000/books/search?query=the

### Get all books
GET http://localhost:3000/books

# should return publisher information and comments as well
### Get a specific book by ID
GET http://localhost:3000/books/14


### Update a book by ID
PUT http://localhost:3000/books/19
Content-Type: application/json

{
  "title": " hello 1",
  "pages": 224
}

# should delete book comment’s as well
### Delete a book by ID
DELETE http://localhost:3000/books/2

# required fields: name
# optional fields: country
### Create a new publisher
POST http://localhost:3000/publishers
Content-Type: application/json

{
 "name": "Marwan",
"country": "Palestine"
}

### Get all publishers
GET http://localhost:3000/publishers

### Get a specific publisher by ID
GET http://localhost:3000/publishers/8

# should not delete publisher if it has any published books
### Delete a publisher by ID
DELETE http://localhost:3000/publishers/9

### GetBooksByPublisher
GET http://localhost:3000/publishers/2/books

### Delete a  comment
DELETE  http://localhost:3000/comments/25

#    required fields: name, comment, book_id
#    optional fields: stars
#    book_id should be an id of existing book
### Create a new comment
POST http://localhost:3000/comments
Content-Type: application/json

{
  "name": "HappyReader2",
  "comment": "Enjoyable2!",
  "BookId": 16
}

# should return top 10 books sorted by AVG stars
# comments without star should be ignored
### Get top-rated books

GET http://localhost:3000/books/top-rated
