
### Sign Up
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "username": "marwan5",
  "email": "marwan@test.com",
  "password": "123123"
}

### Sign In
POST http://localhost:3000/users/signin
Content-Type: application/json

{
  "username": "Marwan5",
  "password": "121212"
}

### Sign Out
GET http://localhost:3000/users/signout
Authorization: 9d516e72-136a-4ac7-bc7f-480bb2deaa3d

### Change Password
PUT http://localhost:3000/users/changePassword
Authorization: 76e013bd-c68d-4179-8c5e-a80691008fb8
Content-Type: application/json

{
  "currentPassword": "123123",
  "newPassword": "121212",
  "confirmPassword": "121212"
}

#     required fields: title, isbn, publisher_id
#     optional fields: year, author, pages
#     publisher_id should be an id of existing publisher
#     isbn should be unique
# Create a new book
###
POST http://localhost:3000/books
Authorization: a9e420fa-3d9b-48c6-afbb-16e736d6e2ca
Content-Type: application/json

{
  "title": "Test7",
  "isbn": "9780314391410",
  "PublisherId": 1,
  "author": "Marwan Samamreh"
}


### Get all books
GET http://localhost:3000/books

# should return publisher information and comments as well
### Get a specific book by ID
GET http://localhost:3000/books/14


### Update a book by ID
PUT http://localhost:3000/books/19
Content-Type: application/json

{
  "title": " hello 1",
  "pages": 224
}

# should delete book comment’s as well
### Delete a book by ID
DELETE http://localhost:3000/books/2

# required fields: name
# optional fields: country
### Create a new publisher
POST http://localhost:3000/publishers
Content-Type: application/json

{
 "name": "Marwan",
"country": "Palestine"
}

### Get all publishers
GET http://localhost:3000/publishers

### Get a specific publisher by ID
GET http://localhost:3000/publishers/8

# should not delete publisher if it has any published books
### Delete a publisher by ID
DELETE http://localhost:3000/publishers/9

### GetBooksByPublisher
GET http://localhost:3000/publishers/2/books

### Delete a  comment
DELETE  http://localhost:3000/comments/25

#    required fields: name, comment, book_id
#    optional fields: stars
#    book_id should be an id of existing book
### Create a new comment
POST http://localhost:3000/comments
Content-Type: application/json

{
  "name": "HappyReader2",
  "comment": "Enjoyable2!",
  "BookId": 16
}

# should return top 10 books sorted by AVG stars
# comments without star should be ignored
### Get top-rated books

GET http://localhost:3000/books/top-rated
